name: error_or

repository: https://github.com/lucafabbri/flutter-error-or

packages:
  - packages/**

ignore:
  - 'packages/**/example'

scripts:
  analyze:
    exec: dart analyze .
  doc:
    exec: dart doc .