name: error_or_plus
description: A simple, fluent discriminated union of an error or a result. Inspired by ErrorOr for .net by Amantiband
version: 0.1.0
repository: https://github.com/lucafabbri/flutter-error-or

environment:
  sdk: ^3.3.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
